### ISSUE TITLE
Expand the query signature?

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/ng-query#6]
We need to check if we REALLY need to support additional overloads.

**Comment by hrvbernardic** [comment]
I suppose [DefaultQueryFunction](https://tanstack.com/query/v4/docs/guides/default-query-function) example is one of the reasons we would want an additional overload.

**Comment by NetanelBasal** [comment]
That's not related. I was referring to the useQuery function.

**Comment by hrvbernardic** [comment]
In the example a query is created just by supplying a queryKey. Currently queryFn is not optional when creating a query.

**Comment by NetanelBasal** [comment]
That's correct.

**Comment by NetanelBasal** [comment]
We need this one, I guess. We need to check the others.

**Comment by hrvbernardic** [comment]
Only reason I could think off for making queryKey param also optional is that we can provide it through queryHash prop of the options object.

**Comment by hrvbernardic** [comment]
Want to do this? I can take this one.

**Comment by NetanelBasal** [comment]
I already did it. Do you want to take another issue?

**Comment by hrvbernardic** [comment]
Sure. Which one?

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/ng-query/issues/9
